### ISSUE TITLE
Remove .jekyll-cache files

### ISSUE THREAD

**Issue by lilyminium** [MobleyLab/mobleylab.org#3]
I think the `.jekyll-cache` files are artifacts of the build process. Could they be added to `.gitignore` https://github.com/MobleyLab/mobleylab.org/blob/gh-pages/.gitignore ?

I think this'll just ignore future changes, so removing the files from the repo will require deleting them and committing that deletion.

**Comment by davidlmobley** [comment]
Closed by #5
