### ISSUE TITLE
Remove Gemfile.lock

### ISSUE THREAD

**Issue by lilyminium** [MobleyLab/mobleylab.org#4]
Could you please also remove Gemfile.lock (i.e. add it to .gitignore and delete the file)? I believe that's the source of the Darwin error in CI: https://github.com/MobleyLab/mobleylab.org/blob/b45861b8a063ae499caf76f1caab5af8dc060289/Gemfile.lock#L78-L79

This line says to only use Mac (Darwin) gems, but our CI is building on Ubuntu. We could change the platform but these leaves future CI to the whims of whoever is maintaining the site.

**Comment by lilyminium** [comment]
If future changes to the repository are made with pull requests (like these https://github.com/MobleyLab/mobleylab.org/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed), it is much easier to preview what is being changed and to ask someone to review!

**Comment by davidlmobley** [comment]
It looks like we already fixed this one; marking as closed.
